set_configuration_string:
  description: 'Sets a string-based configuration value'
  fields:
    entity_id:
      description: 'Fully Instance to configure'
      example: 'fullykiosk.mediaTablet'
    setting:
      description: 'Setting to modify'
      example: 'startUrl'
    value:
      description: 'String value of setting'
      example: 'https://home-assistant.io'